version: '3.8'

services:
  app:
    container_name: my_app
    build:
      context: .

    depends_on:
      - db

    ports:
      - 9999:8000


    env_file:
      - .env-non-dev


  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env-non-dev
